packages:
  - benchmark
  - packages/*
  - packages/mui-envinfo/test
  - packages-internal/*
  - docs
  - test
  - test/moduleResolution
  - apps/*
  - scripts/sizeSnapshot
onlyBuiltDependencies:
  - aws-sdk
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - nx
  - sharp
